### ISSUE TITLE
Sporadically asyncio.TimeoutError during project export

### ISSUE THREAD

**Issue by jloeser** [aplanas/obsgit#12] opened 2020-07-07 11:56 UTC
When exporting a project (from an own OBS instance), roughly one of three attempts fails with:

```
$ ./obsgit -l DEBUG export test:prj ./prj-export
DEBUG:asyncio:Using selector: EpollSelector
Initialized the git repository
Git LFS extension enabled in the repository
...
DEBUG:__main__:End download ...
...
Traceback (most recent call last):
  File "./obsgit", line 1212, in <module>
    loop.run_until_complete(args.func(args, config))
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 488, in run_until_complete
    return future.result()
  File "./obsgit", line 1044, in export
    await exporter.project(project)
  File "./obsgit", line 630, in project
    *(self.git.delete(package) for package in packages_delete),
  File "./obsgit", line 700, in package
    *(self.git.delete(package, filename) for filename in files_delete),
  File "./obsgit", line 106, in download
    await self._download(url_path, filename_path, **params)
  File "./obsgit", line 97, in _download
    chunk = await resp.content.read(1024 * 4)
  File "/home/git-home/obsgit/venv/lib/python3.6/site-packages/aiohttp/streams.py", line 368, in read
    await self._wait('read')
  File "/home/git-home/obsgit/venv/lib/python3.6/site-packages/aiohttp/streams.py", line 296, in _wait
    await waiter
  File "/home/git-home/obsgit/venv/lib/python3.6/site-packages/aiohttp/helpers.py", line 596, in __exit__
    raise asyncio.TimeoutError from None
concurrent.futures._base.TimeoutError
```

Error occurs after a large portion has already be downloaded, the last successfully downloaded file may be different from run to run. Not sure if this may be related to network/server setup. The exported projects has about 12 packages, ~1000 files to download (according to debug output).

```
$ git show-ref --abbrev HEAD
ac6e396 refs/remotes/upstream/HEAD
$ python --version
Python 3.6.10
$ pip list
Package           Version
----------------- -------
aiohttp           3.6.2
async-timeout     3.0.1
asyncio           3.4.3
attrs             19.3.0
cached-property   1.5.1
cffi              1.14.0
chardet           3.0.4
idna              2.9
idna-ssl          1.1.0
multidict         4.7.6
pip               20.1.1
pycparser         2.20
pygit2            1.2.1
setuptools        47.3.1
typing-extensions 3.7.4.2
wheel             0.34.2
yarl              1.4.2
$ osc -A ... api /about
<about>
  <title>Open Build Service API</title>
  <description>API to the Open Build Service</description>
  <revision>2.10.5</revision>
  <last_deployment>2020-05-19 14:34:00 +0200</last_deployment>
  <commit>b8dac32ad172fdad843a31f455a9adff9a3efd71</commit>
</about>
```

**Comment by coolo** [comment] 2020-07-08 05:25
Why use an outdated revision?

**Comment by aplanas** [comment] 2020-07-08 08:07
The Timeout comes from the server. In an older version of obsgit the TO was detected and retry, but for simplification of the code I decided to drop it.

Another aspect is that is easy to DoS OBS with this code, as asyncio can easily hammer the server, but I can implement a better approach this time. In any case the bug is confirmed.

**Comment by jloeser** [comment] 2020-07-08 08:37
Regarding the outdated version: silly me! I've worked on copy of upstream and this copy was always "up-to-date".

Same for https://github.com/aplanas/obsgit/issues/13

**Comment by jloeser** [comment] 2020-08-25 10:02
I face the issue again with latest revision 0d2a585. Before it worked "by accident" when triggering the same export command a second or third time.

Now for one concrete project it seems to always run into this (server) timeout. I checked git history to find mentioned TO detection but wasn't successful.

**Comment by jloeser** [comment] 2020-08-26 07:35
I was just able to reproduce on boo:

```
$ ./obsgit --config ./.obsgitrc-obs export SUSE:SLE-15:GA sle15     
Initialized the git repository
Git LFS extension enabled in the repository
SUSE:SLE-15:GA/opie ...
SUSE:SLE-15:GA/sblim-cmpi-base ...
SUSE:SLE-15:GA/clucene-core ...
SUSE:SLE-15:GA/gnome-menus ...
SUSE:SLE-15:GA/python-azure-mgmt-containerregistry ...
SUSE:SLE-15:GA/python-slip ...
SUSE:SLE-15:GA/libdbi ...
SUSE:SLE-15:GA/liblognorm ...
...
SUSE:SLE-15:GA/createrepo_c ...
SUSE:SLE-15:GA/python-appdirs ...
SUSE:SLE-15:GA/bc ...
SUSE:SLE-15:GA/spice ...
SUSE:SLE-15:GA/python-PyJWT ...
Traceback (most recent call last):
  File "./obsgit", line 1339, in <module>
    loop.run_until_complete(args.func(args, config))
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 488, in run_until_complete
    return future.result()
  File "./obsgit", line 1151, in export
    await exporter.project(project)
  File "./obsgit", line 683, in project
    *(self.git.delete(package) for package in packages_delete),
  File "./obsgit", line 755, in package
    *(self.git.delete(package, filename) for filename in files_delete),
  File "./obsgit", line 106, in download
    await self._download(url_path, filename_path, **params)
  File "./obsgit", line 94, in _download
    async with self.client.get(f"{self.url}/{url_path}", params=params) as resp:
  File "/home/git-home/obsgit/venv/lib/python3.6/site-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/home/git-home/obsgit/venv/lib/python3.6/site-packages/aiohttp/client.py", line 582, in _request
    break
  File "/home/git-home/obsgit/venv/lib/python3.6/site-packages/aiohttp/helpers.py", line 596, in __exit__
    raise asyncio.TimeoutError from None
concurrent.futures._base.TimeoutError
$ git version                                                  
git version 2.26.2
$ pip list                    
Package           Version
----------------- -------
aiohttp           3.6.2
async-timeout     3.0.1
asyncio           3.4.3
attrs             19.3.0
cached-property   1.5.1
cffi              1.14.0
chardet           3.0.4
cryptography      3.0
idna              2.9
idna-ssl          1.1.0
multidict         4.7.6
pip               20.2.2
pycparser         2.20
pygit2            1.2.1
setuptools        47.3.1
six               1.15.0
typing-extensions 3.7.4.2
wheel             0.34.2
yarl              1.4.2
$ git ls -1
* 0d2a585 (HEAD -> master, upstream/master, upstream/HEAD, origin/master) Allows upload of empty data
$ cat .obsgitrc-obs 
[export]
url = https://api.opensuse.org
username = xxx
password = xxx
link = always

[import]
url = https://api.opensuse.org
username = xxx
password = xxx

[storage]
type = lfs

[git]
prefix = packages


```

Traceback looks here a bit different but still TO issue.

**Comment by aplanas** [comment] 2020-08-26 08:53
The current TO is 5*60 secs, that is the default value for the TCPConnector instance. Seems to me that is enough for the client, and is a clear indication that the server (BOO) is under pressure.

Do you see that indeed the TO consume the 5 minutes, or is happening sooner? If you retry, do the TO trigger in a different project?

**Comment by jloeser** [comment] 2020-08-27 08:33
I played around with the TO intervals and set it to 1*60 and 10*60, used `time` for simple measurement:

```
    raise asyncio.TimeoutError from None
concurrent.futures._base.TimeoutError

real	1m5.210s
user	0m9.398s
sys	0m0.814s

```
```
    raise asyncio.TimeoutError from None
concurrent.futures._base.TimeoutError

real	10m27.069s
user	0m24.614s
sys	0m4.524s

```
For me this looks like that it is related to provided TO interval, but also extending the TO (10min) does not help.

Please advice.

**Comment by aplanas** [comment] 2020-08-27 08:47
Still is not clear for me one point. Is it happening under the same package / project? If the command is executed again, is fetching more data and failing in a different package / project, or is advancing?

**Comment by heliocastro** [comment] 2020-08-27 08:51
Hi Alberto

Nope, it happens randomly to me. I tried import from different projects,
and even in my small one, home:heliochissini:carwos, if tails in different
times, sometimes retrigger works

**Comment by aplanas** [comment] 2020-08-27 08:53
@heliocastro I see, so is clearly an OBS load issue. I will implement the automatic re-try to help, but still the root cause of the OBS TO cannot be fixed in obsgit.

**Comment by jloeser** [comment] 2020-08-27 09:43
> Still is not clear for me one point. Is it happening under the same package / project? If the command is executed again, is fetching more data and failing in a different package / project, or is advancing?

Same project (boo/SUSE:SLE-15:GA), first time with TO set to 1min in obsgit, second set TO to 10min.

Running export for the same project using the *same* TO its failing after similar time. Stdout is listing 3334 packages which correlates with the amount of packages in the actual project. Size and amount of files exported to local directory differs from run to run:
```
3335 directories, 19071 files
10483152	sle15.1/
```
```
3335 directories, 7533 files
3304652	sle15.2/
```

**Comment by aplanas** [comment] 2020-08-27 09:49
> Size and amount of files exported to local directory differs from run to run:

Thanks! That is indeed an indication of an OBS issue. As commented, there is nothing that obsgit can do to fix the core problem, but I can do an automatic retry to hide some of the consequences.

As a side note, boo should not be the correct place to fetch SUSE:SLE-15:GA. Do you have access to the internal build service?

**Comment by jloeser** [comment] 2020-08-27 09:55
@aplanas I just used boo to make it reproducible also for others ;)

The core problem is up to the server, that's understood. However having automatic retries or something handling these kind of exceptions would be awesome. We just need to ensure that everything gets exported/imported correclty at the end. I don't care for now how many retries are needed in the background or if every package gets fetched successively.

**Closed** 2020-08-27 11:47 UTC

**Comment by aplanas** [comment] 2020-08-27 11:49
I added a basic retry for the aiohttp methods. In my current internet connection I am not able to reproduce the original issue, so I am not properly tested the decorator. @jloeser can you give a try?

**Comment by jloeser** [comment] 2020-08-28 08:10
First of all I was finally able to export the desired project multiple times without any TO issues using recent rev c49d735 - that's good.

However after these successful exports I re-tried the same with the previous rev 0d2a585 again and it worked, too. Would this mean that by accident the server acts slightly different today as the days before? Adding a log output to the wrapper function indicates that all the functions are executed only once, so no TO error hit at all.

Btw exporting boo/SUSE:SLE-15:GA results in `aiohttp.client_exceptions.ServerDisconnectedError` - but that's OK as boo may be not happy with that amount of parallel requests.

**Comment by aplanas** [comment] 2020-08-28 08:14
> However after these successful exports I re-tried the same with the previous rev [0d2a585](https://github.com/aplanas/obsgit/commit/0d2a585650ccc470f24168c23866e6081e5c1f94) again and it worked, too. Would this mean that by accident the server acts slightly different today as the days before?

I think so, yes. I was not able to reproduce the TO issue with this project. Lets keep the retry code and see in the future.
