### ISSUE TITLE
Very first import for non-existing OBS project fails

### ISSUE THREAD

**Issue by jloeser** [aplanas/obsgit#17] opened 2020-11-02 08:41 UTC
When importing a project to OBS instance which does not exist, the import fails.

Export test project:
```
user:~/tmp> obsgit export home:testuser:test1 test1                                
Initialized the git repository                                                     
Git LFS extension enabled in the repository                                        
home:testuser:test1/obsgit ...                                                     
user:~/tmp> git -C ./test1 add .                                                   
user:~/tmp> git -C ./test1 commit -m "init"                                        
[master aa753e2] init                                                              
 2 files changed, 1 insertion(+), 4 deletions(-)
```

Failing import:
```                            
user:~/tmp> obsgit import home:testuser:test2 ./test1                              
Local git repository is not valid                                                  
user:~/tmp> obsgit import ./test1 home:testuser:test2                              
Git LFS extension enabled in the repository                                        
HTTPException: retry one more time                                                 
Traceback (most recent call last):                                                 
  File "/usr/bin/obsgit", line 1541, in <module>                                   
    loop.run_until_complete(args.func(args, config))                               
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 488, in run_until_complete
    return future.result()                                                         
  File "/usr/bin/obsgit", line 1376, in import_                                    
    await importer.project(project)                                                
  File "/usr/bin/obsgit", line 960, in project                                     
    await self.project_metadata(project)                                           
  File "/usr/bin/obsgit", line 1011, in project_metadata                           
    for meta in metadata                                                           
  File "/usr/bin/obsgit", line 160, in upload                                      
    await self._upload(url_path, filename_path=filename_path, data=data, **params)
  File "/usr/bin/obsgit", line 48, in wrapper                                      
    raise to_exception                                                             
  File "/usr/bin/obsgit", line 36, in wrapper                                      
    return await func(*args, **kwargs)                                             
  File "/usr/bin/obsgit", line 155, in _upload                                     
    raise http.client.HTTPException(f"PUT {resp.status} on {url_path}")            
http.client.HTTPException: PUT 404 on source/home:testuser:test2/_config           
Unclosed client session                                                            
client_session: <aiohttp.client.ClientSession object at 0x7f91a4a789e8>            
Unclosed connector                                                                 
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f91a49a2b28>, 496196.284377881), (<aiohttp.client_proto.ResponseHandler object at 0x7f91a49a2648>, 496196.376519173)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f91a4a78828>            
```

The new target project was created despite the abortion from above. Having now the target project available the second import attempt is successful:
```   
user:~/tmp> osc ls | grep home:testuser:test2                                      
home:testuser:test2                                                                
user:~/tmp> obsgit import ./test1 home:testuser:test2                              
Git LFS extension enabled in the repository                                        
home:testuser:test2/obsgit ...                                                     
user:~/tmp> rpm -q obsgit                                                          
obsgit-0.0.1+git.1604049614.c68f28b-lp151.2.1.noarch
```

**Comment by aplanas** [comment] 2020-11-02 08:50
IIUC this is correct. The error is  `http.client.HTTPException: PUT 404 on source/home:testuser:test2/_config`, seems that the _config file is not valid for the target repo. Try editing the file, or using some of the parameters that do not update the metadata information.

This comes from here: https://github.com/aplanas/obsgit/commit/c8d319bfa949fb008d08f95930ade4ec37c54771. We are more strict about erroring when the metadata do not match in OBS, so we do not accidentally hide any undesired side effect.

I will close this issue, unless we want to change the default behavior (a caution here, because this will break some CI scripts)

**Comment by jloeser** [comment] 2020-11-02 09:23
The exported `test1/.obs/_config` file is just empty as `osc meta prj home:testuser:test1` is. Why should it be invalid?

So what is the desired default behavior? Does the target project have to exist or not?

**Comment by aplanas** [comment] 2020-11-02 09:25
Uhm indeed, an empty _config should not produce 404. I will try to reproduce in the public OBS

**Comment by jloeser** [comment] 2020-11-02 09:29
> osc meta prj home:testuser:test1

I meant `osc meta prjconf ...` obviously.

**Closed** 2020-11-02 09:48 UTC

**Comment by aplanas** [comment] 2020-11-02 09:49
I think that I understand the issue. Because this part is totally async, sometimes was uploading _config before the _meta. I changed the code to other the uploads. In my local tests seems that this fix the issue.

Thanks for reporting, and sorry for the noise!

**Comment by jloeser** [comment] 2020-11-02 13:56
Looks good now - thanks for fixing :+1:
