### ISSUE TITLE
Crash on 2nd import

### ISSUE THREAD

**Issue by coolo** [aplanas/obsgit#3] opened 2020-06-16 06:17 UTC
To workaround issue #1, I tried to reimport the same git revisions and this ended in 

```
DEBUG:__main__:End upload to source/home:coolo:carwos-import/python-semanage/_meta
DEBUG:__main__:End upload to source/home:coolo:carwos-import/libnettle/_attribute
DEBUG:__main__:End upload to source/home:coolo:carwos-import/libnettle/_meta
Traceback (most recent call last):
  File "./obsgit", line 1128, in <module>
    asyncio.run(args.func(args, config))
  File "/usr/lib64/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib64/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "./obsgit", line 1041, in import_
    await importer.project(project)
  File "./obsgit", line 742, in project
    await asyncio.gather(
  File "./obsgit", line 778, in package
    files_md5_obs, _ = await self.obs.files_md5_revision(project, package)
  File "./obsgit", line 215, in files_md5_revision
    root = await self._xml(f"/source/{project}/{package}", rev=revision)
  File "./obsgit", line 186, in _xml
    async with self.client.get(f"{self.url}/{url_path}", params=params) as resp:
  File "/usr/lib64/python3.8/site-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/usr/lib64/python3.8/site-packages/aiohttp/client.py", line 464, in _request
    req = self._request_class(
  File "/usr/lib64/python3.8/site-packages/aiohttp/client_reqrep.py", line 263, in __init__
    url2 = url.with_query(params)
  File "/usr/lib64/python3.8/site-packages/yarl/__init__.py", line 922, in with_query
    new_query = self._get_str_query(*args, **kwargs)
  File "/usr/lib64/python3.8/site-packages/yarl/__init__.py", line 885, in _get_str_query
    query = "&".join(
  File "/usr/lib64/python3.8/site-packages/yarl/__init__.py", line 886, in <genexpr>
    quoter(k) + "=" + quoter(self._query_var(v)) for k, v in query.items()
  File "/usr/lib64/python3.8/site-packages/yarl/__init__.py", line 861, in _query_var
    raise TypeError(
TypeError: Invalid variable type: value should be str or int, got None of type <class 'NoneType'>
ERROR:asyncio:Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f822519aa90>
ERROR:asyncio:Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f822487fb20>, 11301923.529252866), (<aiohttp.client_proto.ResponseHandler object at 0x7f82254514c0>, 11301923.536545279), (<aiohttp.client_proto.ResponseHandler object at 0x7f8224868ca0>, 11301923.589475935), (<aiohttp.client_proto.ResponseHandler object at 0x7f82248c8fa0>, 11301923.590759516)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f822519ac40>

**Comment by aplanas** [comment] 2020-06-16 09:52
Should be fixed (not able to reproduce the same issue) https://github.com/aplanas/obsgit/commit/0a5ab9eea39e084b493261bfeb9d6a7bd8400dd1

**Closed by aplanas** 2020-06-16 09:52 UTC
